[package]
name = "rustybuzz"
version = "0.2.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
edition = "2018"
description = "An incremental harfbuzz port to Rust."
documentation = "https://docs.rs/rustybuzz/"
readme = "README.md"
repository = "https://github.com/RazrFalcon/rustybuzz"
license = "MIT"
keywords = ["text", "shaping", "opentype", "truetype"]
categories = ["text-processing"]
exclude = ["benches/**"]

[dependencies]
bitflags = "1.2"
smallvec = "1.4"
ttf-parser = { git = "https://github.com/laurmaedje/ttf-parser", branch = "rb-ggg" }
unicode-bidi-mirroring = "0.1"
unicode-ccc = "0.1"
unicode-general-category = "0.2"
unicode-script = "0.5"

[dev-dependencies]
pico-args = "0.3"
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
